### ISSUE TITLE
TODO Parser

### ISSUE THREAD

**Issue by unkn0wn107** [ZEDIUM-Off/MiniRT#7]
- [x] Plusieurs shapes
- [x] Vérif extension.rt sinon erreur
- [x] Vérif unicité des A, C tout le temps et L pour IS_MANDATORY
- [ ] Vérif vecteurs normalisés en entrée
- [x] Autres types d'espaces entre les paramètres
- [x] Light blanche pour IS_MANDATORY
